### ISSUE TITLE
Switch to published version of web-tree-sitter-0.20.5

### ISSUE THREAD

**Issue by wenkokke** [cursorless-dev/vscode-parse-tree#29]
A new version of web-tree-sitter has finally been published to NPM!
https://www.npmjs.com/package/web-tree-sitter/v/0.20.5

We should probably keep the machinery for hand rolling our own version around, but we can now switched to simply using the latest published version! (If our tests pass.)

**Comment by pokey** [comment]
Sounds good! Are we sure we want to keep the hand-rolling machinery around? It will be in the git history if we find we need it again. We could tag the last commit that has it and leave a note in the readme.

I guess if we think it's very likely we'll need it again soon, it's probably worth keeping around, but otherwise I prefer to remove code when we can

**Comment by wenkokke** [comment]
I’d no longer suggest this, as web-tree-sitter releases are sparse and not timed with actual tree-sitter releases.
